name: DevOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Display Files
      run: ls

    - name: Build Step
      run: echo "Building the website..."

    - name: Test Step
      run: echo "Testing the website..."
